platform :ios, '8.0'
target ‘WisdomSiteSuiNing’ do

#加载网络图片第三方
pod 'SDWebImage', '~> 4.3.3'

#网络请求库
pod 'AFNetworking', '~> 3.2.1'
#下拉刷新
pod 'MJRefresh', '~> 3.1.15.3'

#提示框
pod 'MBProgressHUD', '~> 1.1.0'
#百度地图第三方
pod 'BaiduMap-iOS-SDK', '~> 3.0'
#二维码扫描
pod 'ZBarSDK', '~> 1.3.1'

pod 'SocketRocket', '~> 0.5.1'
#代码适配的第三方
pod 'Masonry', '~> 1.1.0'
end


